language: node_js

node_js:
 - "0.10"
 - "0.8"
 - "0.6"

before_install:
 - sudo apt-get -qq update

install:
 - npm install mocha

before_script:
 - npm install
 - npm test

script:
 - make clean
 - sudo apt-get -qq install libgdal1-dev
 - npm install --shared_gdal
 - npm test
 - make clean
 - sudo apt-add-repository --yes ppa:ubuntugis/ubuntugis-unstable
 - sudo apt-get -qq update
 - sudo apt-get -qq install libgdal1-dev
 - npm install --shared_gdal
 - npm test
